framework:
    mailer:
        envelope:
            sender: 'dream.sw.eng.2.project@gmail.com'
        dsn: '%env(MAILER_DSN)%'
        headers:
            from: 'DREAM <dream.sw.eng.2.project@gmail.com>'
